name: Build and Publish
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Publish
      run: |
        make
        mkdir -p bin
        mv Part-A.exe bin/
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Part-A
        path: bin/Part-A.exe

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: Part-A
        path: bin
